apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
- path: helm/kyverno-playground/charts/kyverno-playground
  contents:
  - path: .
    git:
      url: https://github.com/kyverno/playground
      ref: kyverno-playground-chart-v0.10.2
    includePaths:
    - charts/kyverno-playground/**/*
    newRootPath: charts/kyverno-playground